version: '3.8'

services:
    dev:
        container_name: poll_app_server_dev
        image: poll-app-server-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        depends_on:
            - mongodb
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: poll_app_server_prod
        image: poll-app-server-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        depends_on:
            - mongodb
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    mongodb:
        image : mongo:latest
        container_name: mongodb
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        networks:
            - nesjs-network
        restart: always

networks:
    nesjs-network:
        